version: "3"

services:
  graphdb:
    image: dhlabbasel/graphdb-free
    ports:
      - 7200:7200
    depends_on:
      - salsah
    volumes:
      - ../../graphdb-free/graphdb:/graphdb

  knora:
    image: nieine/knora:5-fix
    ports:
      - 3333:3333
    depends_on:
      - graphdb
    volumes:
     # - ./Knora/application.conf:/webapi/config/application.conf
      - ../../tmp:/tmp
    environment:
    - KNORA_WEBAPI_TRIPLESTORE_HOST=graphdb
    - KNORA_WEBAPI_SIPI_INTERNAL_HOST=sipi
    - KNORA_WEBAPI_TRIPLESTORE_DBTYPE=graphdb-free

  sipi:
    image: dhlabbasel/sipi:develop
    container_name: sipi
    ports:
      - "1024:1024"
    volumes:
      - ../../Sipi/sipi/config:/sipi/config
      - ../../Sipi/sipi/scripts:/sipi/scripts
      - ../../tmp:/tmp
      - $HOME:$HOME
      - ../../Sipi/sipi/images:/sipi/images
      - ../../Sipi/sipi/server:/sipi/server
    restart: unless-stopped
    command: --config=/sipi/config/sipi.knora-docker-it-config.lua

  salsah:
    image: nieine/salsah:2de55f5
    ports:
      - 4200:4200

  fuseki:
   image: nieine/fuseki:2019-10-31v2
   entrypoint: ./fuseki-server
   environment:
     - FUSEKI_HOME=/apache-jena-fuseki-3.13.1/
     - JENA_HOME=/apache-jena-fuseki-3.13.1/
   ports:
     - 3030:3030 # external:internal
   volumes:
     - ../../fuseki/apache-jena-fuseki-3.13.1/run/shiro.ini:/apache-jena-fuseki-3.13.1/
     - ../../fuseki/apache-jena-fuseki-3.13.1/scripts:/apache-jena-fuseki-3.13.1/scripts
     - ../../fuseki/apache-jena-fuseki-3.13.1/lib/fuseki-server.jar:/apache-jena-fuseki-3.13.1/lib/fuseki-server.jar # needed for tdb2loader


  #nieos:
  #  build: ./NIE-OS
  #  ports:
  #  - 4300:4200
  #  entrypoint: ng s --host 0.0.0.0 --disable-host-check
  #  environment:
  #  - VIRTUAL_HOST=nieos.localhost

  #node:
  #  build: ./NIE-OS
  #  ports:
  #  - 4000:3000
  #  entrypoint: npm run start:server
  #    environment:
  #    - VIRTUAL_HOST=node.localhost

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

